# Generated by Django 5.1.4 on 2024-12-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('Modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('Anio', models.CharField(max_length=4, verbose_name='Año')),
                ('Placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('Disponibilidad', models.BooleanField(default=True)),
                ('Color', models.CharField(max_length=20)),
            ],
        ),
    ]
