# Generated by Django 5.1.4 on 2024-12-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='Color',
        ),
    ]
